- name: Create a directory for Zabbix
  file:
        path: /opt/zabbix
        state: directory
        mode: '0755'

# Copy Docker Compose file for Zabbix
- name: Copy Zabbix Docker Compose file
  copy:
    dest: /opt/zabbix/docker-compose.yml
    content: |
      version: '3.5'
      services:
        mysql:
          image: mysql:5.7
          container_name: zabbix-mysql
          restart: unless-stopped
          environment:
            MYSQL_DATABASE: zabbix
            MYSQL_USER: zabbix
            MYSQL_PASSWORD: zabbixpass
            MYSQL_ROOT_PASSWORD: rootpass
          volumes:
            - /opt/zabbix/mysql:/var/lib/mysql
          networks:
            - zabbix-net

        zabbix-server:
          image: zabbix/zabbix-server-mysql:latest
          container_name: zabbix-server
          restart: unless-stopped
          environment:
            DB_SERVER_HOST: mysql
            MYSQL_DATABASE: zabbix
            MYSQL_USER: zabbix
            MYSQL_PASSWORD: zabbixpass
          depends_on:
            - mysql
          ports:
            - "10051:10051"
          networks:
            - zabbix-net

        zabbix-web:
          image: zabbix/zabbix-web-nginx-mysql:latest
          container_name: zabbix-web
          restart: unless-stopped
          environment:
            DB_SERVER_HOST: mysql
            MYSQL_DATABASE: zabbix
            MYSQL_USER: zabbix
            MYSQL_PASSWORD: zabbixpass
            ZBX_SERVER_HOST: zabbix-server
          depends_on:
            - zabbix-server
          ports:
            - "8081:8080"
          networks:
            - zabbix-net

      networks:
        zabbix-net:
          driver: bridge

# Start Zabbix using Docker Compose
- name: Start Zabbix with Docker Compose
  command: docker-compose up -d
  args:
    chdir: /opt/zabbix
